version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: product_db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        
    
    domain-service:
        image: domain-service:latest
        container_name: domain-service
        build:
            context: Domain-servise
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8090:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin

volumes:
    pgadmin_data:
        driver: local