version: '3.8'

services:
    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: product_db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    domain-service:
        image: domain-service:latest
        build:
            context: Domain-service
            dockerfile: Dockerfile
        container_name: domain-service
        restart: unless-stopped
        ports:
            - "8081:8081"
            - "50051:50051"
        depends_on:
            - postgres
            - rabbitmq
            - redis

    gateway:
        image: gateway:latest
        build:
            context: Gateway
        container_name: gateway
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - domain-service

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8090:80"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    redis:
        image: redis:7.0
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        command: [ "redis-server", "--appendonly", "yes" ]

    elasticsearch:
        image: elasticsearch:8.8.0
        container_name: elasticsearch
        restart: always
        ports:
            - "9200:9200"
        environment:
            discovery.type: single-node
            xpack.security.enrollment.enabled: "true"
            xpack.security.enabled: "false"
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    kibana:
        image: kibana:8.8.0
        container_name: kibana
        restart: on-failure
        environment:
            - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch

    logstash:
        image: logstash:8.8.0
        container_name: logstash
        restart: unless-stopped
        ports:
            - "5044:5044"
            - "5000:5000"
        environment:
            LS_JAVA_OPTS: "-Xms512m -Xmx512m"
        volumes:
            - ./logstash/pipeline:/usr/share/logstash/pipeline
        depends_on:
            - elasticsearch
            - rabbitmq

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: on-failure
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_PASSWORD: "admin"
        depends_on:
            - prometheus

volumes:
    pgadmin_data:
        driver: local
